// Static SEO / marketing copy for the Rent Receipt Generator page.
// Pulled out of RentReceiptPage.jsx so the page file is about behaviour and
// this file is about words — the two change for different reasons.

export const SEO_TITLE = "Free Rent Receipt Generator Online — HRA Claim PDF (2026)";
export const SEO_DESCRIPTION = "Generate a rent receipt online for free. Create HRA-compliant rent receipts with landlord PAN, tenant name, property address and payment details. No login. Instant PDF. India-compliant.";
export const CANONICAL = "https://www.opstools.ai/documents/rent-receipt";

export const softwareAppSchema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "OpsTools Rent Receipt Generator", operatingSystem: "Web", applicationCategory: "BusinessApplication", offers: { "@type": "Offer", price: "0", priceCurrency: "INR" }, description: SEO_DESCRIPTION, url: CANONICAL, provider: { "@type": "Organization", name: "OpsTools", url: "https://www.opstools.ai" } };

export const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [{ "@type": "Question", name: "Is this rent receipt generator free?", acceptedAnswer: { "@type": "Answer", text: "Yes, completely free with no login required. Generate unlimited rent receipts at no cost." } }, { "@type": "Question", name: "Is the rent receipt valid for HRA exemption?", acceptedAnswer: { "@type": "Answer", text: "Yes. The receipt includes all fields required for HRA exemption claims — tenant name, landlord name, PAN, property address, rent amount, and period." } }, { "@type": "Question", name: "Is landlord PAN mandatory on rent receipt?", acceptedAnswer: { "@type": "Answer", text: "Landlord PAN is mandatory if annual rent exceeds ₹1 lakh (i.e. monthly rent above ₹8,333). It is always good practice to include it for HRA claims." } }, { "@type": "Question", name: "What is a revenue stamp on rent receipt?", acceptedAnswer: { "@type": "Answer", text: "A revenue stamp of ₹1 is required on rent receipts when the rent amount exceeds ₹5,000 per month and payment is made in cash. For digital/cheque payments, a revenue stamp is not required." } }, { "@type": "Question", name: "Can I download the rent receipt as PDF?", acceptedAnswer: { "@type": "Answer", text: "Yes. Click Save PDF to directly download the receipt as a PDF file — no print dialog needed." } }, { "@type": "Question", name: "How many months of rent receipts do I need for HRA?", acceptedAnswer: { "@type": "Answer", text: "Most employers require month-wise rent receipts for each month you are claiming HRA. Generate one receipt per month with the correct period." } }] };

export const INTRO = (<><p style={{ marginBottom: 16 }}>Generating a rent receipt in India used to mean downloading a Word template, formatting it manually, or asking your landlord to write one. OpsTools Rent Receipt Generator makes it instant — pick a template, fill in the details, see the receipt live, and download a PDF in seconds. No login, no subscription.</p><p style={{ marginBottom: 16 }}>The receipt is designed for HRA (House Rent Allowance) exemption claims and includes all fields that Indian employers and the Income Tax department require: tenant name, landlord name and PAN, property address, rent amount in figures and words, payment method, and period.</p><p>Whether you are a salaried employee claiming HRA at year-end or a landlord issuing receipts to tenants, this tool covers you. Your data never leaves your browser.</p></>);

export const WHAT_IS = `A rent receipt is a document issued by a landlord acknowledging that rent has been received from a tenant. In India, rent receipts are primarily used by salaried employees to claim House Rent Allowance (HRA) exemption under Section 10(13A) of the Income Tax Act.`;

export const WHY_USE = [{ title: "HRA tax exemption", body: "Salaried employees need rent receipts to claim HRA exemption from income tax." }, { title: "Landlords issuing receipts", body: "Issue professional, properly formatted receipts to tenants." }, { title: "Proof of residence", body: "Rent receipts serve as address proof for various KYC purposes." }, { title: "Reimbursement claims", body: "A properly formatted receipt speeds up the HR approval process." }];

export const FEATURES = [{ icon: "🧾", title: "4 receipt templates", body: "Certificate, Duplicate Book, Minimal, and Formal Table — pick the style that fits." }, { icon: "🔢", title: "Amount in words", body: "Automatically converts rent amount to words on supported templates." }, { icon: "⬇️", title: "Direct PDF download", body: "One click downloads the receipt as a PDF." }, { icon: "📦", title: "Bulk generation", body: "Upload a CSV to generate many receipts at once." }, { icon: "🔒", title: "100% private", body: "No data is stored or transmitted." }, { icon: "🆓", title: "No login needed", body: "Single receipts are always free." }];

export const HOW_TO_STEPS = [{ step: 1, title: "Choose a template", body: "Pick from 4 receipt styles." }, { step: 2, title: "Fill receipt details", body: "Enter the receipt number, date, and rental period." }, { step: 3, title: "Enter rent amount", body: "Type the monthly rent." }, { step: 4, title: "Add property & parties", body: "Enter property address, tenant, and landlord details." }, { step: 5, title: "Preview your receipt", body: "Check the live preview." }, { step: 6, title: "Download PDF", body: "Click Save to download." }];

export const BENEFITS = ["4 templates to choose from.", "Bulk generation via CSV upload.", "Amount in words auto-generated.", "Landlord PAN field for Income Tax compliance.", "All data stays in your browser.", "Completely free — no subscription."];

export const FORMAT_FIELDS = [{ field: "Receipt No.", description: "Unique serial number for the receipt", example: "001" }, { field: "Date", description: "Date of payment / receipt issue", example: "01 June 2026" }, { field: "Tenant Name", description: "Full name of the person paying rent", example: "Rajesh Verma" }, { field: "Rent Amount", description: "Monthly rent in figures and words", example: "₹15,000" }, { field: "Property Address", description: "Full address of the rented property", example: "Flat 4B, Sunrise Apartments, Andheri West, Mumbai" }, { field: "Period", description: "Month and year of rent payment", example: "June 2026" }, { field: "Payment Method", description: "How rent was paid", example: "Cash / Cheque / NEFT / UPI" }, { field: "Landlord Name", description: "Full name of the property owner", example: "Ramesh Kumar" }, { field: "Landlord PAN", description: "PAN of landlord (mandatory if annual rent > ₹1 lakh)", example: "ABCDE1234F" }];

export const FAQS = faqSchema.mainEntity.map((i) => ({ q: i.name, a: i.acceptedAnswer.text }));

export const RELATED_DOCS = [{ name: "Fuel Bill Generator", href: "/documents/fuel-bill", description: "Petrol & diesel receipts for reimbursement." }, { name: "GST Invoice Generator", href: "/documents/gst-invoice", description: "Tax-compliant GST invoices." }, { name: "Salary Slip Generator", href: "/documents/salary-slip", description: "Professional payslips." }];

export const BREADCRUMBS = [
  { name: "Home", url: "https://www.opstools.ai" },
  { name: "Documents", url: "https://www.opstools.ai/documents" },
  { name: "Rent Receipt Generator", url: CANONICAL },
];
