// Static SEO / marketing copy for the Vehicle Expense Report page.
// Pulled out of VehicleExpensePage.jsx so the page file is about behaviour and
// this file is about words — the two change for completely different reasons.

export const SEO_TITLE = "Free Vehicle Expense Report Generator — Employee Reimbursement & Fleet Management (2026)";
export const SEO_DESCRIPTION = "Generate a vehicle expense report online for free. Track fuel, tolls, maintenance and mileage for employee reimbursement or fleet management. No login. Instant PDF.";
export const CANONICAL = "https://www.opstools.ai/documents/vehicle-expense";

export const softwareAppSchema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "OpsTools Vehicle Expense Report Generator", operatingSystem: "Web", applicationCategory: "BusinessApplication", offers: { "@type": "Offer", price: "0", priceCurrency: "INR" }, description: SEO_DESCRIPTION, url: CANONICAL, provider: { "@type": "Organization", name: "OpsTools", url: "https://www.opstools.ai" } };

export const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [{ "@type": "Question", name: "Is this vehicle expense report generator free to use?", acceptedAnswer: { "@type": "Answer", text: "Yes, completely free with no login required." } }, { "@type": "Question", name: "Can I track expenses for more than one vehicle?", acceptedAnswer: { "@type": "Answer", text: "Yes. Switch to Fleet Management mode to add multiple vehicles and see a per-vehicle expense breakdown." } }, { "@type": "Question", name: "Does it calculate distance travelled?", acceptedAnswer: { "@type": "Answer", text: "Yes, in Employee Reimbursement mode — enter the odometer start and end reading for a trip and the distance is calculated automatically." } }, { "@type": "Question", name: "Does this generate a PDF?", acceptedAnswer: { "@type": "Answer", text: "Yes. Click Save PDF to directly download the report as a PDF file." } }] };

export const INTRO = (<><p style={{ marginBottom: 16 }}>Claiming travel expenses or tracking fleet costs usually means wrestling with a spreadsheet or waiting on your accounts team. OpsTools Vehicle Expense Report Generator turns it into a two-minute job. Fill in the details, and get a print-ready report covering fuel, tolls, parking, maintenance and more — no login, no subscription.</p><p>Two modes cover the two most common use cases: Employee Reimbursement, which tracks a single vehicle with odometer-based distance for a travel claim, and Fleet Management, which tracks multiple vehicles at once with a per-vehicle expense breakdown. The preview updates live as you type, and your data never leaves your device.</p></>);

export const WHAT_IS = `A vehicle expense report is a structured record of costs incurred while using a vehicle for work — fuel, tolls, parking, maintenance and repairs. It is used to support employee reimbursement claims and to track running costs across a fleet of vehicles.`;

export const WHY_USE = [{ title: "Employee travel reimbursement", body: "Log every trip-related expense against a report number your accounts team can approve." }, { title: "Fleet expense tracking", body: "See total spend broken down by vehicle across your whole fleet in one report." }, { title: "Business mileage records", body: "Odometer-based distance tracking supports mileage-based reimbursement policies." }, { title: "Tax and audit documentation", body: "Keep a clean, dated record of vehicle-related business expenses." }, { title: "Replacing lost receipts", body: "Misplaced a fuel or toll receipt? Log the expense manually before your reimbursement deadline." }];

export const FEATURES = [{ icon: "👤", title: "Two report modes", body: "Employee Reimbursement for a single vehicle, Fleet Management for many." }, { icon: "🚗", title: "Multi-vehicle support", body: "Add as many vehicles as your fleet needs, each with its own expense total." }, { icon: "📏", title: "Automatic distance calculation", body: "Enter odometer start/end and the trip distance is calculated for you." }, { icon: "👁️", title: "Live preview", body: "See the report update in real time as you fill the form." }, { icon: "⬇️", title: "Direct PDF download", body: "One click downloads the report as a PDF — no print dialog needed." }, { icon: "📱", title: "Mobile-friendly", body: "Works on iPhone, Android, and any tablet." }, { icon: "🔒", title: "100% private", body: "No data is stored or transmitted. Everything happens in your browser." }, { icon: "🆓", title: "No login needed", body: "No account, no email, no credit card." }];

export const HOW_TO_STEPS = [{ step: 1, title: "Choose a mode", body: "Employee Reimbursement for one vehicle, or Fleet Management for several." }, { step: 2, title: "Fill in report details", body: "Report number, period covered, and the approver's name." }, { step: 3, title: "Add employee or fleet details", body: "Enter employee details and a vehicle, or add every vehicle in your fleet." }, { step: 4, title: "Log expense entries", body: "Add each fuel, toll, parking or maintenance expense as its own line item." }, { step: 5, title: "Preview your report", body: "Check the live preview — totals and breakdowns update instantly." }, { step: 6, title: "Download PDF", body: "Click Save PDF to download the report directly to your device." }];

export const BENEFITS = ["Generate unlimited expense reports — no caps or credit limits.", "No registration or sign-up required.", "Automatic distance and total calculations.", "Separate modes for individual and fleet-wide tracking.", "All data stays in your browser — zero privacy risk.", "Completely free — no subscription."];

export const FORMAT_FIELDS = [{ field: "Report No.", description: "Unique identifier for the expense report", example: "VEH-2026-3737" }, { field: "Period", description: "Date range the report covers", example: "01/09/2026 – 30/09/2026" }, { field: "Employee / Fleet Details", description: "Employee info, or the list of fleet vehicles", example: "Rajesh Sharma, EMP-1042" }, { field: "Vehicle Reg. No.", description: "Registration number of the vehicle used", example: "MH12AB1234" }, { field: "Expense Type", description: "Category of the expense entry", example: "Fuel / Toll / Parking / Maintenance" }, { field: "Odometer Reading", description: "Start and end reading for distance-based entries", example: "12000 → 12150 (150 km)" }, { field: "Amount", description: "Cost of the individual expense entry", example: "₹850.00" }];

export const FAQS = faqSchema.mainEntity.map((i) => ({ q: i.name, a: i.acceptedAnswer.text }));

export const RELATED_DOCS = [{ name: "Fuel Bill Generator", href: "/documents/fuel-bill", description: "Petrol & diesel receipts, 4 Indian formats." }, { name: "Rent Receipt Generator", href: "/documents/rent-receipt", description: "HRA-compliant rent receipts." }, { name: "Salary Slip Generator", href: "/documents/salary-slip", description: "Professional payslips." }];

export const BREADCRUMBS = [
  { name: "Home", url: "https://www.opstools.ai" },
  { name: "Documents", url: "https://www.opstools.ai/documents" },
  { name: "Vehicle Expense Report", url: CANONICAL },
];
