/**
 * programmaticPages.js
 *
 * The master registry for all OpsTools programmatic SEO pages.
 * Each entry = one URL, one document generator, one SEO package.
 *
 * HOW THE ENGINE WORKS:
 *   1. Every page imports DocumentPageSEO + useSEO
 *   2. It passes its own config (title, description, faqs, fields, etc.)
 *   3. All structure/layout/schema injection is shared
 *   4. Only the content data is unique per page
 *
 * To launch a new page:
 *   1. Add an entry here
 *   2. Create /src/pages/documents/[Slug]Page.jsx with the content config
 *   3. Add a route in App.jsx
 *   4. Push to Vercel → auto-deploys
 *
 * SEO PRIORITY:
 *   P1 = build now (high search volume, easy content)
 *   P2 = build in 30 days
 *   P3 = build in 90 days
 */

export const PROGRAMMATIC_PAGES = [

  // ───────────────────────────────────────────────────────────────
  // TRANSPORT & FUEL
  // ───────────────────────────────────────────────────────────────
  {
    slug: "fuel-bill",
    name: "Fuel Bill Generator",
    category: "Transport",
    url: "/documents/fuel-bill",
    primaryKeyword: "fuel bill generator",
    searchVolume: "High",
    priority: "P1 — LIVE",
    title: "Free Fuel Bill Generator Online — Petrol & Diesel Bill PDF (2026)",
    description: "Generate a fuel bill online for free. IOCL, POS & thermal formats. Instant PDF, no login required.",
    targetAudience: ["employees claiming reimbursement", "petrol station operators", "fleet managers"],
  },
  {
    slug: "petrol-bill",
    name: "Petrol Bill Generator",
    category: "Transport",
    url: "/documents/petrol-bill",
    primaryKeyword: "petrol bill generator",
    searchVolume: "High",
    priority: "P1",
    title: "Free Petrol Bill Generator — Download Petrol Receipt PDF Online (2026)",
    description: "Create a petrol bill online in seconds. IOCL, POS and thermal formats. No login. Instant PDF.",
    note: "Thin variant of fuel-bill page targeting 'petrol' keyword specifically. Canonical → /documents/fuel-bill",
  },
  {
    slug: "diesel-bill",
    name: "Diesel Bill Generator",
    category: "Transport",
    url: "/documents/diesel-bill",
    primaryKeyword: "diesel bill generator",
    searchVolume: "Medium",
    priority: "P1",
    title: "Free Diesel Bill Generator — Diesel Receipt PDF Download (2026)",
    description: "Generate a diesel bill for reimbursement or records. Free, instant PDF, no sign-up.",
  },
  {
    slug: "cng-bill",
    name: "CNG Bill Generator",
    category: "Transport",
    url: "/documents/cng-bill",
    primaryKeyword: "CNG bill generator",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free CNG Bill Generator — CNG Receipt with GSTIN (2026)",
    description: "Generate a CNG gas station bill with GSTIN. Free online CNG receipt generator for reimbursement.",
  },
  {
    slug: "vehicle-expense-report",
    name: "Vehicle Expense Report",
    category: "Transport",
    url: "/documents/vehicle-expense-report",
    primaryKeyword: "vehicle expense report generator",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free Vehicle Expense Report Generator — Fuel & Maintenance (2026)",
    description: "Create a vehicle expense report with fuel, maintenance and mileage costs. Free PDF generator.",
  },
  {
    slug: "mileage-reimbursement",
    name: "Mileage Reimbursement Form",
    category: "Transport",
    url: "/documents/mileage-reimbursement",
    primaryKeyword: "mileage reimbursement form India",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free Mileage Reimbursement Form Generator India (2026)",
    description: "Generate a km-based travel reimbursement form. Free PDF, India-specific rates.",
  },
  {
    slug: "cab-receipt",
    name: "Cab / Taxi Receipt Generator",
    category: "Transport",
    url: "/documents/cab-receipt",
    primaryKeyword: "cab receipt generator India",
    searchVolume: "High",
    priority: "P1",
    title: "Free Cab Receipt Generator — Taxi Bill PDF for Reimbursement (2026)",
    description: "Create a cab or taxi receipt for expense claims. Free, instant PDF, no login.",
  },
  {
    slug: "toll-receipt",
    name: "Toll Receipt Generator",
    category: "Transport",
    url: "/documents/toll-receipt",
    primaryKeyword: "toll receipt generator",
    searchVolume: "Low",
    priority: "P3",
    title: "Free Toll Receipt Generator — Fastag & Manual Toll Bill (2026)",
    description: "Generate a toll receipt for highway expense reimbursement. Free PDF tool.",
  },

  // ───────────────────────────────────────────────────────────────
  // REIMBURSEMENT
  // ───────────────────────────────────────────────────────────────
  {
    slug: "travel-expense-report",
    name: "Travel Expense Report",
    category: "Reimbursement",
    url: "/documents/travel-expense-report",
    primaryKeyword: "travel expense report generator India",
    searchVolume: "High",
    priority: "P1",
    title: "Free Travel Expense Report Generator India (2026)",
    description: "Create a complete travel expense report with fuel, food, stay and transport. Free PDF.",
  },
  {
    slug: "medical-reimbursement",
    name: "Medical Reimbursement Form",
    category: "Reimbursement",
    url: "/documents/medical-reimbursement",
    primaryKeyword: "medical reimbursement form generator",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free Medical Reimbursement Form Generator (2026)",
    description: "Generate a medical expense reimbursement form for employee HR submission. Free PDF.",
  },
  {
    slug: "food-reimbursement",
    name: "Food / Meal Allowance Claim",
    category: "Reimbursement",
    url: "/documents/food-reimbursement",
    primaryKeyword: "meal allowance claim form India",
    searchVolume: "Low",
    priority: "P3",
    title: "Free Meal Allowance Claim Form Generator India (2026)",
    description: "Create a food or meal allowance claim form for office reimbursement. Free PDF.",
  },
  {
    slug: "internet-reimbursement",
    name: "Internet Reimbursement Form",
    category: "Reimbursement",
    url: "/documents/internet-reimbursement",
    primaryKeyword: "internet reimbursement form generator",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free Internet Bill Reimbursement Form Generator (2026)",
    description: "Generate an internet expense reimbursement claim form for remote work allowance. Free PDF.",
  },

  // ───────────────────────────────────────────────────────────────
  // RETAIL & INVOICING
  // ───────────────────────────────────────────────────────────────
  {
    slug: "gst-invoice",
    name: "GST Invoice Generator",
    category: "Retail",
    url: "/documents/gst-invoice",
    primaryKeyword: "GST invoice generator India",
    searchVolume: "Very High",
    priority: "P1",
    title: "Free GST Invoice Generator India — GST Bill PDF Online (2026)",
    description: "Create a GST-compliant tax invoice with GSTIN, HSN codes, CGST/SGST/IGST. Free, instant PDF.",
  },
  {
    slug: "proforma-invoice",
    name: "Proforma Invoice Generator",
    category: "Retail",
    url: "/documents/proforma-invoice",
    primaryKeyword: "proforma invoice generator India",
    searchVolume: "High",
    priority: "P1",
    title: "Free Proforma Invoice Generator India (2026)",
    description: "Create a professional proforma invoice for advance payment requests. Free PDF, GST-ready.",
  },
  {
    slug: "cash-memo",
    name: "Cash Memo Generator",
    category: "Retail",
    url: "/documents/cash-memo",
    primaryKeyword: "cash memo generator India",
    searchVolume: "High",
    priority: "P1",
    title: "Free Cash Memo Generator India — Cash Bill PDF (2026)",
    description: "Create a cash memo or retail cash bill online. Free, instant PDF, no registration.",
  },
  {
    slug: "delivery-challan",
    name: "Delivery Challan Generator",
    category: "Retail",
    url: "/documents/delivery-challan",
    primaryKeyword: "delivery challan generator India",
    searchVolume: "High",
    priority: "P1",
    title: "Free Delivery Challan Generator India (2026)",
    description: "Create a GST delivery challan for goods dispatch. Free PDF, no login required.",
  },
  {
    slug: "purchase-order",
    name: "Purchase Order Generator",
    category: "Retail",
    url: "/documents/purchase-order",
    primaryKeyword: "purchase order generator India",
    searchVolume: "High",
    priority: "P2",
    title: "Free Purchase Order Generator India — PO Format PDF (2026)",
    description: "Generate a professional purchase order in standard Indian PO format. Free PDF.",
  },
  {
    slug: "credit-note",
    name: "Credit Note Generator",
    category: "Retail",
    url: "/documents/credit-note",
    primaryKeyword: "credit note generator GST India",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free GST Credit Note Generator India (2026)",
    description: "Create a GST-compliant credit note for returns, discounts, or corrections. Free PDF.",
  },
  {
    slug: "debit-note",
    name: "Debit Note Generator",
    category: "Retail",
    url: "/documents/debit-note",
    primaryKeyword: "debit note generator India",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free GST Debit Note Generator India (2026)",
    description: "Generate a GST debit note for shortages or price corrections. Free, instant PDF.",
  },
  {
    slug: "quotation",
    name: "Quotation Generator",
    category: "Retail",
    url: "/documents/quotation",
    primaryKeyword: "quotation generator India",
    searchVolume: "High",
    priority: "P1",
    title: "Free Quotation Generator India — Business Quote PDF (2026)",
    description: "Create a professional business quotation in seconds. Free PDF, GST-ready.",
  },
  {
    slug: "payment-receipt",
    name: "Payment Receipt Generator",
    category: "Retail",
    url: "/documents/payment-receipt",
    primaryKeyword: "payment receipt generator India",
    searchVolume: "High",
    priority: "P1",
    title: "Free Payment Receipt Generator India (2026)",
    description: "Generate a payment acknowledgement receipt. Free PDF, works for cash and online payments.",
  },

  // ───────────────────────────────────────────────────────────────
  // HOSPITALITY
  // ───────────────────────────────────────────────────────────────
  {
    slug: "hotel-bill",
    name: "Hotel Bill Generator",
    category: "Hospitality",
    url: "/documents/hotel-bill",
    primaryKeyword: "hotel bill generator India",
    searchVolume: "High",
    priority: "P1",
    title: "Free Hotel Bill Generator India — Hotel Invoice PDF (2026)",
    description: "Create a hotel invoice or accommodation bill for business travel reimbursement. Free PDF.",
  },
  {
    slug: "restaurant-bill",
    name: "Restaurant Bill Generator",
    category: "Hospitality",
    url: "/documents/restaurant-bill",
    primaryKeyword: "restaurant bill generator India",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free Restaurant Bill Generator — Food Invoice PDF (2026)",
    description: "Create a restaurant invoice with GST. Free PDF, no login needed.",
  },
  {
    slug: "event-invoice",
    name: "Event / Venue Invoice",
    category: "Hospitality",
    url: "/documents/event-invoice",
    primaryKeyword: "event invoice generator India",
    searchVolume: "Low",
    priority: "P3",
    title: "Free Event Invoice Generator India (2026)",
    description: "Create a catering or venue invoice for events. Free GST-ready PDF.",
  },

  // ───────────────────────────────────────────────────────────────
  // HEALTHCARE
  // ───────────────────────────────────────────────────────────────
  {
    slug: "medical-bill",
    name: "Medical Bill Generator",
    category: "Healthcare",
    url: "/documents/medical-bill",
    primaryKeyword: "medical bill generator India",
    searchVolume: "High",
    priority: "P1",
    title: "Free Medical Bill Generator India — Hospital Invoice PDF (2026)",
    description: "Create a medical or hospital bill for insurance claims or reimbursement. Free PDF.",
  },
  {
    slug: "pharmacy-bill",
    name: "Pharmacy Bill Generator",
    category: "Healthcare",
    url: "/documents/pharmacy-bill",
    primaryKeyword: "pharmacy bill generator India",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free Pharmacy Bill Generator India (2026)",
    description: "Create a medical store or pharmacy bill. Free PDF with GST fields.",
  },
  {
    slug: "doctor-receipt",
    name: "Doctor Consultation Receipt",
    category: "Healthcare",
    url: "/documents/doctor-receipt",
    primaryKeyword: "doctor consultation receipt generator",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free Doctor Consultation Receipt Generator India (2026)",
    description: "Generate a doctor fee receipt for medical insurance or reimbursement claims. Free PDF.",
  },
  {
    slug: "diagnostic-bill",
    name: "Diagnostic / Lab Bill",
    category: "Healthcare",
    url: "/documents/diagnostic-bill",
    primaryKeyword: "diagnostic lab bill generator India",
    searchVolume: "Low",
    priority: "P3",
    title: "Free Diagnostic Lab Bill Generator India (2026)",
    description: "Create a pathology or diagnostic centre bill. Free PDF, HSN/SAC codes supported.",
  },

  // ───────────────────────────────────────────────────────────────
  // EDUCATION
  // ───────────────────────────────────────────────────────────────
  {
    slug: "fee-receipt",
    name: "School / College Fee Receipt",
    category: "Education",
    url: "/documents/fee-receipt",
    primaryKeyword: "school fee receipt generator India",
    searchVolume: "High",
    priority: "P1",
    title: "Free School Fee Receipt Generator India (2026)",
    description: "Create a school or college fee receipt for parents. Free PDF, no login.",
  },
  {
    slug: "tuition-receipt",
    name: "Tuition Fee Receipt",
    category: "Education",
    url: "/documents/tuition-receipt",
    primaryKeyword: "tuition fee receipt generator",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free Tuition Fee Receipt Generator India (2026)",
    description: "Generate a coaching or private tuition receipt. Free PDF, instantly downloadable.",
  },
  {
    slug: "library-fine-receipt",
    name: "Library Fine Receipt",
    category: "Education",
    url: "/documents/library-fine-receipt",
    primaryKeyword: "library fine receipt generator",
    searchVolume: "Low",
    priority: "P3",
    title: "Free Library Fine Receipt Generator (2026)",
    description: "Create a library fine or late fee receipt for institutional use. Free PDF.",
  },

  // ───────────────────────────────────────────────────────────────
  // UTILITY & PROPERTY
  // ───────────────────────────────────────────────────────────────
  {
    slug: "rent-receipt",
    name: "Rent Receipt Generator",
    category: "Utility",
    url: "/documents/rent-receipt",
    primaryKeyword: "rent receipt generator India",
    searchVolume: "Very High",
    priority: "P1",
    title: "Free Rent Receipt Generator India — HRA Rent Receipt PDF (2026)",
    description: "Create HRA-compliant rent receipts for tenants and landlords. Free PDF, IT-ready.",
  },
  {
    slug: "electricity-bill",
    name: "Electricity Bill Generator",
    category: "Utility",
    url: "/documents/electricity-bill",
    primaryKeyword: "electricity bill generator India",
    searchVolume: "High",
    priority: "P2",
    title: "Free Electricity Bill Generator India (2026)",
    description: "Create a sample electricity or power bill for records. Free PDF.",
  },
  {
    slug: "water-bill",
    name: "Water Bill Generator",
    category: "Utility",
    url: "/documents/water-bill",
    primaryKeyword: "water bill generator India",
    searchVolume: "Medium",
    priority: "P3",
    title: "Free Water Bill Generator India (2026)",
    description: "Generate a water utility bill for records or reimbursement. Free PDF.",
  },
  {
    slug: "maintenance-bill",
    name: "Society Maintenance Bill",
    category: "Utility",
    url: "/documents/maintenance-bill",
    primaryKeyword: "society maintenance bill generator India",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free Society Maintenance Bill Generator India (2026)",
    description: "Create a housing society maintenance bill. Free PDF with GST fields.",
  },
  {
    slug: "internet-bill",
    name: "Internet Bill Generator",
    category: "Utility",
    url: "/documents/internet-bill",
    primaryKeyword: "internet bill generator India",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free Internet Bill Generator India (2026)",
    description: "Generate a broadband or internet bill for office reimbursement. Free PDF.",
  },
  {
    slug: "mobile-bill",
    name: "Mobile / Phone Bill",
    category: "Utility",
    url: "/documents/mobile-bill",
    primaryKeyword: "mobile bill generator India",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free Mobile Bill Generator India (2026)",
    description: "Create a mobile phone bill for business or personal reimbursement. Free PDF.",
  },

  // ───────────────────────────────────────────────────────────────
  // HR & PAYROLL
  // ───────────────────────────────────────────────────────────────
  {
    slug: "salary-slip",
    name: "Salary Slip Generator",
    category: "HR",
    url: "/documents/salary-slip",
    primaryKeyword: "salary slip generator India",
    searchVolume: "Very High",
    priority: "P1",
    title: "Free Salary Slip Generator India — Payslip PDF (2026)",
    description: "Create professional salary slips with CTC, deductions, net pay. Free PDF, HR-ready.",
  },
  {
    slug: "offer-letter",
    name: "Offer Letter Generator",
    category: "HR",
    url: "/documents/offer-letter",
    primaryKeyword: "offer letter generator India",
    searchVolume: "High",
    priority: "P1",
    title: "Free Offer Letter Generator India (2026)",
    description: "Create a professional job offer letter. Free PDF, legally structured.",
  },
  {
    slug: "experience-letter",
    name: "Experience Letter Generator",
    category: "HR",
    url: "/documents/experience-letter",
    primaryKeyword: "experience letter generator India",
    searchVolume: "High",
    priority: "P1",
    title: "Free Experience Letter Generator India (2026)",
    description: "Generate an employee experience or relieving letter. Free PDF, professional format.",
  },
  {
    slug: "appointment-letter",
    name: "Appointment Letter Generator",
    category: "HR",
    url: "/documents/appointment-letter",
    primaryKeyword: "appointment letter generator India",
    searchVolume: "High",
    priority: "P1",
    title: "Free Appointment Letter Generator India (2026)",
    description: "Create a formal employee appointment letter. Free PDF, HR-compliant.",
  },
  {
    slug: "leave-application",
    name: "Leave Application Generator",
    category: "HR",
    url: "/documents/leave-application",
    primaryKeyword: "leave application generator India",
    searchVolume: "Very High",
    priority: "P1",
    title: "Free Leave Application Generator India (2026)",
    description: "Generate a formal leave application letter in seconds. Free PDF.",
  },
  {
    slug: "noc-letter",
    name: "NOC Letter Generator",
    category: "HR",
    url: "/documents/noc-letter",
    primaryKeyword: "NOC letter generator India",
    searchVolume: "High",
    priority: "P2",
    title: "Free NOC Letter Generator India — No Objection Certificate (2026)",
    description: "Create a no objection certificate for employees, tenants or vehicles. Free PDF.",
  },

  // ───────────────────────────────────────────────────────────────
  // LEGAL & AGREEMENTS
  // ───────────────────────────────────────────────────────────────
  {
    slug: "rental-agreement",
    name: "Rental Agreement Generator",
    category: "Legal",
    url: "/documents/rental-agreement",
    primaryKeyword: "rental agreement generator India",
    searchVolume: "Very High",
    priority: "P1",
    title: "Free Rental Agreement Generator India (2026)",
    description: "Create a rental or lease agreement for residential or commercial property. Free PDF.",
  },
  {
    slug: "service-agreement",
    name: "Service Agreement Generator",
    category: "Legal",
    url: "/documents/service-agreement",
    primaryKeyword: "service agreement generator India",
    searchVolume: "Medium",
    priority: "P2",
    title: "Free Service Agreement Generator India (2026)",
    description: "Generate a service contract between client and vendor. Free PDF, legally structured.",
  },
  {
    slug: "affidavit",
    name: "Affidavit Generator",
    category: "Legal",
    url: "/documents/affidavit",
    primaryKeyword: "affidavit generator India",
    searchVolume: "High",
    priority: "P2",
    title: "Free Affidavit Generator India (2026)",
    description: "Create a self-declaration affidavit for various purposes. Free PDF template.",
  },
];

export default PROGRAMMATIC_PAGES;
